package domain

import "time"

type TransactionStatus string

const (
	TxPending    TransactionStatus = "pending"
	TxSuccessful TransactionStatus = "successful"
	TxFailed     TransactionStatus = "failed"
	TxRefunded   TransactionStatus = "refunded"
)

type PaymentAttemptStatus string

const (
	AttemptInitializing    PaymentAttemptStatus = "initializing"
	AttemptActive          PaymentAttemptStatus = "active"
	AttemptCancelRequested PaymentAttemptStatus = "cancel_requested"
	AttemptCancelled       PaymentAttemptStatus = "cancelled"
	AttemptSuperseded      PaymentAttemptStatus = "superseded"
	AttemptFailed          PaymentAttemptStatus = "failed"
	AttemptSuccessful      PaymentAttemptStatus = "successful"
)

// Transaction represents the core Payment record managed by the system.
type Transaction struct {
	ID               string            `json:"id"`
	CustomerID       string            `json:"customer_id"`
	BookingID        string            `json:"booking_id"`
	QuoteID          string            `json:"quote_id"`
	AmountCents      int64             `json:"amount_cents"`
	Amount           float64           `json:"amount"` // Derived major-unit amount for legacy API/provider contracts.
	Currency         string            `json:"currency"`
	Provider         string            `json:"provider"` // e.g., "nomba"
	Method           string            `json:"method"`   // e.g., "card", "crypto", "transfer"
	Status           TransactionStatus `json:"status"`
	InternalRef      string            `json:"internal_ref"` // Unique ref generated by our system
	ProviderRef      string            `json:"provider_ref"` // Ref returned by the provider
	CurrentAttemptID *string           `json:"current_attempt_id,omitempty"`
	Metadata         map[string]string `json:"metadata"`
	CreatedAt        time.Time         `json:"created_at"`
	UpdatedAt        time.Time         `json:"updated_at"`
}

// PaymentAttempt represents a single provider-side checkout session for a logical transaction.
type PaymentAttempt struct {
	ID                     string               `json:"id"`
	TransactionID          string               `json:"transaction_id"`
	AttemptNo              int                  `json:"attempt_no"`
	Provider               string               `json:"provider"`
	Status                 PaymentAttemptStatus `json:"status"`
	InternalRef            string               `json:"internal_ref"`
	ProviderRef            string               `json:"provider_ref"`
	CheckoutURL            string               `json:"checkout_url"`
	ReturnURL              string               `json:"return_url"`
	ReturnContext          string               `json:"return_context"`
	ReturnContextExpiresAt *time.Time           `json:"return_context_expires_at,omitempty"`
	CancelRequestedAt      *time.Time           `json:"cancel_requested_at,omitempty"`
	CancelledAt            *time.Time           `json:"cancelled_at,omitempty"`
	SupersededByAttemptID  *string              `json:"superseded_by_attempt_id,omitempty"`
	CreatedByUserID        string               `json:"created_by_user_id"`
	CreatedAt              time.Time            `json:"created_at"`
	UpdatedAt              time.Time            `json:"updated_at"`
}
